### PR TITLE
Gnome 45 support

### PR DESCRIPTION
**Pull request by ionutbortis**
Hi!

Since I recently upgraded to 45 I thought I could lend a hand and port your extension as well. It seems to work fine on my machine.

I tried to keep the code changes minimal but FYI, the guys reviewing gnome extensions have stricter guidelines now. If they will reject this submission, please let me know and I'll do my best to make the necessary changes.

Also, do you plan on maintaining this extension in the future?

If not, please think about an ownership transfer. We have a github organization for unmaintained gnome extensions, [Extensions Valhalla](https://github.com/Extensions-Valhalla). So far we manage only one extension, but if you're too busy, we would gladly accept your extension. The goal is to provide minimum support for new gnome releases.

Thanks!

### CODE REVIEW

**Comment by IBBoard** [comment]
Only just started using it, but it seems to be working for me 🙂 Thanks!

**Comment by khimaros** [comment]
@ionutbortis thank you for this pull request. looks reasonable overall.

i will try to get a GNOME 45 environment set up so that i can test this in the coming days.

as of now, i'm still interested in maintaining this project. however,, release cadence is likely to continue tracking with debian testing, as that's what i use on all of my devices.

**Comment by ionutbortis** [comment]
@khimaros 

Cool, glad to hear that you didn't abandon this project! 

I see that debian testing has gnome-shell 44.5, only the experimental branch has the latest 45... Maybe using a vm for minimum code changes when new gnome versions pop out? 

Personally, I use a Fedora Rawhide vm in Virtual Box that I update from time to time. That seems to work fine, so far.

**Comment by ShaunTheSalvo** [comment]
Just gave this a test, and it seems to be working fine! I installed it using ionutbortis's instructions at https://extensions.gnome.org/extension/4736/smart-auto-move/.

Installed, rebooted, activated the extension and it worked. Looking good so far. I'll do some more testing over the next few days.

**Comment by Tyrbiter** [comment]
Starting to see this failing to find some app windows in the Saved Windows tab, can't find where the selected window details are stored either.

**Comment by KataFF** [comment]
Works as advertised on GNOME Shell 45.3 on Manjaro:
image

**Comment by khimaros** [comment]
@KataFF to clarify, is that the modified version from this PR or the one from the extension store?

**Comment by Rammani28** [comment]
What should I do to enable this extension in my system? 
image

**Comment by ionutbortis** [comment]
@Rammani28 

Unfortunately, the owner of the extension said that he's using debian testing which is still on gnome shell 44. I guess the extension will be officially updated to 45 only when debian testing will get there... :cry: 

You could try to manually install the build I did that contains this pull request. Run these terminal commands followed by a re-login:
```
wget https://github.com/khimaros/smart-auto-move/files/13418637/smart-auto-move%40khimaros.com.shell-extension.zip

gnome-extensions install --force smart-auto-move@khimaros.com.shell-extension.zip
```

**Comment by khimaros** [comment]
i'm happy to say that this seems to be working well for gnome-shell 45, 46, and the unreleased nightlies. the code looks fine to me and i will be merging this momentarily and pushing a release to EGO.

**Pull request merged**
